### PR TITLE
Terminate conference

### PR DESCRIPTION
**Pull request by calvinckho**
add event listeners to terminate the conference #75

### CODE REVIEW

**Comment by woellinger** [comment]
Hi Calvin, could you please publish this change to NPM? The current version 2.2.1 on NPM does not contain this fix.
TIA Wolfgang

**Comment by calvinckho** [comment]
Hi @woellinger, I just published 2.3.0-beta.0 on npm. Please try to install it and let me know if it runs okay. It has incorporated the latest terminate-conference features.

**Comment by woellinger** [comment]
Hi Calvin,

I get the following error when I build my App:

> Task :capacitor-jitsi-meet:generateDebugRFile FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':capacitor-jitsi-meet:generateDebugRFile'.
> Could not resolve all files for configuration
':capacitor-jitsi-meet:debugCompileClasspath'.
> Could not resolve
com.github.MatrixFrog:android-scalablevideoview:v1.0.4-jitpack.
Required by:
project :capacitor-jitsi-meet >
com.facebook.react:react-native-video:5.2.0-jitsi-10639879
> Could not resolve
com.github.MatrixFrog:android-scalablevideoview:v1.0.4-jitpack.
> Could not get resource '
https://dl.bintray.com/ionic-team/capacitor/com/github/MatrixFrog/android-scala
blevideoview/v1.0.4-jitpack/android-scalablevideoview-v1.0.4-jitpack.pom'.
> Could not HEAD '
https://dl.bintray.com/ionic-team/capacitor/com/github/MatrixFrog/android-scalablevi
deoview/v1.0.4-jitpack/android-scalablevideoview-v1.0.4-jitpack.pom'.
> Connection reset

**Comment by calvinckho** [comment]
in the project's build.gradle, you need to add maven { url 'https://www.jitpack.io' }.

```gradle
allprojects {
    repositories {
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Pull request merged**
