### PR TITLE
update mobile sdks to 8.6.3

### PR DESCRIPTION
**Pull request by gasci**
update the mobile sdks to 8.6.3
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

### CODE REVIEW

**Comment by gasci** [comment]
@calvinckho I see that the "Wait for the moderator button" cannot be translated even after changing the system language in the phone with the SDK 8.6.0. Everthing else is translated, though. Maybe they fixed it at 8.6.3

**Comment by calvinckho** [comment]
@gasci I just merged your PR. Please try to install the branch and test it.

**Comment by gasci** [comment]
Thank you. Should you update the release tag for me to see the change? 4.1.0 is still using 8.6.0.

**Comment by calvinckho** [comment]
@gasci can you test the code first by installing from Github?

`npm i git+ssh://git@github.com:calvinckho/capacitor-jitsi-meet#master`

I normally only do a npm release after testing the code thoroughly on both Android and iOS. If you can do that and let me know they run well, then I will make the 4.1.1 npm release.

Thanks.

**Pull request merged**
