### PR TITLE
Jitsi authentication

### PR DESCRIPTION
**Pull request by cyril-colin**

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Really? is it working?

**Comment by cyril-colin** [comment]
As I said in https://github.com/calvinckho/capacitor-jitsi-meet/issues/26#issuecomment-688954931 This build success (android and ios) but not test completely because my jisti server instance has not yet the plugin to manage the JWT.

Some informations here : https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

**Comment by DanielnetoDotCom** [comment]
I did test , I fork and modified with your changes .

Unfortunately does not work. I checked the logs still not submitted the jwt

**Comment by cyril-colin** [comment]
Tested with a server installed thanks to their docker https://github.com/jitsi/docker-jitsi-meet and JWT enabled server side : 
this work well both on android and iOS

**Comment by calvinckho** [comment]
Hi @cyril-colin. Great work on adding the token param. You missed one thing. It is adding the param in definitions.ts. I have modified it in https://github.com/calvinckho/capacitor-jitsi-meet/tree/add-token and am testing it. Please also test it and if it works I will merge it.

**Comment by calvinckho** [comment]
The new code is released in 1.5.0. It is working fine on my iOS and Android (without providing a token). @cyril-colin @DanielnetoDotCom can you install and it with token and see if you are able to authenticate with your video bridge?

**Pull request merged**
